name: Deploy to Azure

on:
  push:
    branches: ["main"]
  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run:
          npm install

      - name: 'Login to Azure Subscription'
        uses: azure/login@v1
        with: 
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build Next.js app
        run: |
          npm run build
          mv .next/static .next/standalone/.next/static
          # mv public .nexty/standalone/public
      
      - name: Deploy
        shell: pwsh
        runs: |
          $ZIP_FILE_NAME = "./${FILE_NAME}.zip"
          zip $ZIP_FILE_NAME ./* .next -qr

          az webapp deploy `
            --resource-group $RESOURCE_GROUP_NAME `
            --name $WEB_APP_NAME `
            --src-path $ZIP_FILE_NAME `
            --slot production `
            --type zip `
            --clean true

        -env:
          FILE_NAME: main
          RESOURCE_GROUP_NAME: "rg-uks"
          WEB_APP_NAME: "satestinguks"
